gesdinet_jwt_refresh_token:
    ttl_update: true
    refresh_token_class: App\Entity\RefreshToken
    ttl: 7200 # 2h in seconds
    single_use: true

    cookie:
        enabled: true
        remove_token_from_body: true
        http_only: true
        same_site: strict
        secure: true
        path: /api/token
        domain: null